title: "Markus' spontaneous writings & thoughts."
description: "This is a place I can dump some material from my brain. Maybe it'll even be interesting to some wandering lost soul out there. I write about anything that interest me, and I try to keep a large variety of topics & themes throughout :)"
